### PR TITLE
Update StringExtensions.cs

### PR DESCRIPTION
**Pull request by kiko81**
Overloads with less parameters may be used

### CODE REVIEW

**Comment by vladislav-karamfilov** [comment]
What is the benefit of this change?

**Comment by kiko81** [comment]
29b... and the look. Behind the scenes no improvement.
Since this is supposed to be used "as is" less size is ok

**Comment by vladislav-karamfilov** [comment]
OK. With your changes in the `GetStringBetween()` method there is no need to set the `startFrom` parameter to 0 [here](https://github.com/kiko81/MissingFeatures.NET/blob/815027917eb64a666788deffb2f0fa74fdbe8940/MissingFeatures/StringExtensions.cs#L15). Let's remove this line.

**Comment by kiko81** [comment]
True

**Review by vladislav-karamfilov — APPROVED** [review]

**Pull request merged**
